//! Coq Proof Export
//!
//! Generates Coq proof code from ZK circuit constraints.

use super::{ProofExporter, ProofObligation, ProofResult, ProofSystem};
use crate::analysis::symbolic::{SymbolicConstraint, SymbolicValue};
use zk_core::ConstraintEquation;
use zk_core::FieldElement;

/// Coq proof exporter
pub struct CoqExporter {
    /// Field modulus
    field_modulus: String,
    /// Include standard library
    include_stdlib: bool,
}

impl CoqExporter {
    pub fn new(field_modulus: &str) -> Self {
        Self {
            field_modulus: field_modulus.to_string(),
            include_stdlib: true,
        }
    }

    /// Generate Coq header with imports
    fn generate_header(&self, module_name: &str) -> String {
        let mut header = String::new();

        header.push_str("(*\n");
        header.push_str("  Auto-generated Coq proof for ZK circuit verification\n");
        header.push_str("  Generated by ZkPatternFuzz\n");
        header.push_str("*)\n\n");

        if self.include_stdlib {
            header.push_str("Require Import Coq.ZArith.ZArith.\n");
            header.push_str("Require Import Coq.micromega.Lia.\n");
            header.push_str("Require Import Coq.Lists.List.\n");
            header.push_str("Import ListNotations.\n\n");
        }

        header.push_str(&format!("Module {}.\n\n", module_name));

        // Define the field
        header.push_str("(* BN254 scalar field *)\n");
        header.push_str(&format!(
            "Definition p : Z := {}%Z.\n\n",
            self.field_modulus
        ));

        // Define field type
        header.push_str("(* Field element type *)\n");
        header.push_str("Definition F := { x : Z | 0 <= x < p }.\n\n");

        // Field operations
        header.push_str("(* Field operations modulo p *)\n");
        header.push_str("Definition fadd (a b : Z) : Z := (a + b) mod p.\n");
        header.push_str("Definition fmul (a b : Z) : Z := (a * b) mod p.\n");
        header.push_str("Definition fsub (a b : Z) : Z := (a - b + p) mod p.\n");
        header.push_str("Definition fneg (a : Z) : Z := (p - a) mod p.\n\n");

        header
    }

    /// Generate Coq footer
    fn generate_footer(&self, module_name: &str) -> String {
        format!("\nEnd {}.\n", module_name)
    }

    /// Convert symbolic value to Coq expression
    fn value_to_coq(value: &SymbolicValue) -> String {
        match value {
            SymbolicValue::Concrete(fe) => {
                format!("{}%Z", fe.to_decimal_string())
            }
            SymbolicValue::Symbol(name) => {
                // Convert to valid Coq identifier
                let clean: String = name
                    .chars()
                    .map(|c| if c.is_alphanumeric() { c } else { '_' })
                    .collect();
                clean
            }
            SymbolicValue::Add(a, b) => {
                format!("(fadd {} {})", Self::value_to_coq(a), Self::value_to_coq(b))
            }
            SymbolicValue::Mul(a, b) => {
                format!("(fmul {} {})", Self::value_to_coq(a), Self::value_to_coq(b))
            }
            SymbolicValue::Sub(a, b) => {
                format!("(fsub {} {})", Self::value_to_coq(a), Self::value_to_coq(b))
            }
            SymbolicValue::Neg(a) => {
                format!("(fneg {})", Self::value_to_coq(a))
            }
            _ => "0%Z".to_string(),
        }
    }

    /// Convert symbolic constraint to Coq proposition
    fn constraint_to_coq(constraint: &SymbolicConstraint) -> String {
        match constraint {
            SymbolicConstraint::Eq(a, b) => {
                format!("{} = {}", Self::value_to_coq(a), Self::value_to_coq(b))
            }
            SymbolicConstraint::Neq(a, b) => {
                format!("{} <> {}", Self::value_to_coq(a), Self::value_to_coq(b))
            }
            SymbolicConstraint::R1CS { a, b, c } => {
                format!(
                    "fmul {} {} = {}",
                    Self::value_to_coq(a),
                    Self::value_to_coq(b),
                    Self::value_to_coq(c)
                )
            }
            SymbolicConstraint::Boolean(v) => {
                format!(
                    "({} = 0%Z \\/ {} = 1%Z)",
                    Self::value_to_coq(v),
                    Self::value_to_coq(v)
                )
            }
            SymbolicConstraint::And(c1, c2) => {
                format!(
                    "({} /\\ {})",
                    Self::constraint_to_coq(c1),
                    Self::constraint_to_coq(c2)
                )
            }
            SymbolicConstraint::Or(c1, c2) => {
                format!(
                    "({} \\/ {})",
                    Self::constraint_to_coq(c1),
                    Self::constraint_to_coq(c2)
                )
            }
            SymbolicConstraint::Not(c) => {
                format!("~({})", Self::constraint_to_coq(c))
            }
            SymbolicConstraint::True => "True".to_string(),
            SymbolicConstraint::False => "False".to_string(),
            _ => "True".to_string(),
        }
    }

    /// Generate an obligation for a constraint equation.
    fn equation_to_obligation(&self, eq: &ConstraintEquation, idx: usize) -> String {
        let mut obligation = String::new();

        if let Some(ref desc) = eq.description {
            obligation.push_str(&format!("(* {} *)\n", desc));
        }

        let mut vars: Vec<usize> = eq
            .a_terms
            .iter()
            .chain(eq.b_terms.iter())
            .chain(eq.c_terms.iter())
            .map(|(idx, _)| *idx)
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();
        vars.sort_unstable();

        obligation.push_str(&format!(
            "Definition constraint_{}_obligation : Prop :=\n",
            idx
        ));
        obligation.push_str("  forall ");
        for var in &vars {
            obligation.push_str(&format!("(x{} : Z) ", var));
        }
        obligation.push_str(",\n  ");

        for (i, var) in vars.iter().enumerate() {
            if i > 0 {
                obligation.push_str(" ->\n  ");
            }
            obligation.push_str(&format!("(0 <= x{} < p)", var));
        }

        let a_expr = self.linear_combination_to_coq(&eq.a_terms);
        let b_expr = self.linear_combination_to_coq(&eq.b_terms);
        let c_expr = self.linear_combination_to_coq(&eq.c_terms);
        obligation.push_str(&format!(
            " ->\n  fmul ({}) ({}) = ({}).\n\n",
            a_expr, b_expr, c_expr
        ));

        obligation.push_str(&format!(
            "Theorem constraint_{}_identity :\n  constraint_{}_obligation -> constraint_{}_obligation.\n",
            idx, idx, idx
        ));
        obligation.push_str("Proof.\n");
        obligation.push_str("  intros H.\n");
        obligation.push_str("  exact H.\n");
        obligation.push_str("Qed.\n\n");

        obligation
    }

    /// Convert linear combination to Coq expression
    fn linear_combination_to_coq(&self, terms: &[(usize, FieldElement)]) -> String {
        if terms.is_empty() {
            return "0%Z".to_string();
        }

        let term_strs: Vec<String> = terms
            .iter()
            .map(|(idx, coeff)| {
                if coeff.is_one() {
                    format!("x{}", idx)
                } else {
                    format!("fmul {}%Z x{}", coeff.to_decimal_string(), idx)
                }
            })
            .collect();

        if term_strs.len() == 1 {
            term_strs[0].clone()
        } else {
            // Fold additions
            let mut result = term_strs[0].clone();
            for term in &term_strs[1..] {
                result = format!("fadd ({}) ({})", result, term);
            }
            result
        }
    }
}

impl ProofExporter for CoqExporter {
    fn system(&self) -> ProofSystem {
        ProofSystem::Coq
    }

    fn export_obligation(&self, obligation: &ProofObligation) -> ProofResult {
        let mut code = String::new();

        code.push_str(&format!("(* {} *)\n", obligation.description));
        code.push_str(&format!(
            "Definition {}_obligation : Prop :=\n  ",
            obligation.name
        ));

        if !obligation.variables.is_empty() {
            code.push_str("forall ");
            for var in &obligation.variables {
                code.push_str(&format!("({} : Z) ", var));
            }
            code.push_str(",\n  ");
        }

        let pre_strs: Vec<String> = obligation
            .preconditions
            .iter()
            .map(Self::constraint_to_coq)
            .collect();

        if !pre_strs.is_empty() {
            code.push_str(&pre_strs.join(" ->\n  "));
            code.push_str(" ->\n  ");
        }

        let goals: Vec<String> = obligation
            .postconditions
            .iter()
            .map(Self::constraint_to_coq)
            .collect();

        if goals.is_empty() {
            code.push_str("True");
        } else {
            code.push_str(&goals.join(" /\\ "));
        }

        code.push_str(".\n\n");
        code.push_str(&format!(
            "Theorem {} : {}_obligation -> {}_obligation.\n",
            obligation.name, obligation.name, obligation.name
        ));
        code.push_str("Proof.\n");
        code.push_str("  intros H.\n");
        code.push_str("  exact H.\n");
        code.push_str("Qed.\n");

        ProofResult {
            code,
            extension: "v",
            success: true,
            system: ProofSystem::Coq,
            dependencies: vec!["Coq.ZArith.ZArith".to_string()],
            warnings: vec![
                "Obligation-style output: provide external proofs for *_obligation statements."
                    .to_string(),
            ],
        }
    }

    fn export_module(&self, name: &str, obligations: &[ProofObligation]) -> ProofResult {
        let mut code = self.generate_header(name);

        for obligation in obligations {
            let result = self.export_obligation(obligation);
            code.push_str(&result.code);
            code.push('\n');
        }

        code.push_str(&self.generate_footer(name));

        ProofResult {
            code,
            extension: "v",
            success: true,
            system: ProofSystem::Coq,
            dependencies: vec!["Coq.ZArith.ZArith".to_string()],
            warnings: vec![],
        }
    }

    fn export_circuit(&self, name: &str, constraints: &[ConstraintEquation]) -> ProofResult {
        let mut code = self.generate_header(name);

        code.push_str("(* Circuit constraint lemmas *)\n\n");

        for (i, eq) in constraints.iter().enumerate() {
            code.push_str(&self.equation_to_obligation(eq, i));
        }

        code.push_str("(* Main soundness obligation *)\n");
        code.push_str("Parameter constraint_satisfied : (nat -> Z) -> nat -> Prop.\n");
        code.push_str("Parameter circuit_valid : (nat -> Z) -> Prop.\n\n");
        code.push_str(&format!(
            "Definition {}_soundness_obligation : Prop :=\n",
            name.to_lowercase()
        ));
        code.push_str("  forall (witness : nat -> Z),\n");
        code.push_str("  (forall i, 0 <= witness i < p) ->\n");
        code.push_str("  (forall i, constraint_satisfied witness i) ->\n");
        code.push_str("  circuit_valid witness.\n\n");
        code.push_str(&format!(
            "Theorem {}_soundness_identity :\n  {}_soundness_obligation -> {}_soundness_obligation.\n",
            name.to_lowercase(),
            name.to_lowercase(),
            name.to_lowercase()
        ));
        code.push_str("Proof.\n");
        code.push_str("  intros H.\n");
        code.push_str("  exact H.\n");
        code.push_str("Qed.\n");

        code.push_str(&self.generate_footer(name));

        ProofResult {
            code,
            extension: "v",
            success: true,
            system: ProofSystem::Coq,
            dependencies: vec!["Coq.ZArith.ZArith".to_string()],
            warnings: vec![
                "Obligation-style circuit output: prove *_obligation definitions externally."
                    .to_string(),
            ],
        }
    }

    fn generate_skeleton(&self, obligation: &ProofObligation) -> String {
        format!(
            "(* Proof obligation template for {} *)\n(* Goal: {} *)\nDefinition {}_obligation : Prop := True.",
            obligation.name, obligation.description, obligation.name
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_coq_exporter_creation() {
        let exporter = CoqExporter::new(
            "21888242871839275222246405745257275088548364400416034343698204186575808495617",
        );
        assert_eq!(exporter.system(), ProofSystem::Coq);
    }

    #[test]
    fn test_value_to_coq() {
        let sym = SymbolicValue::Symbol("x".to_string());
        assert_eq!(CoqExporter::value_to_coq(&sym), "x");

        let add = SymbolicValue::Add(
            Box::new(SymbolicValue::Symbol("x".to_string())),
            Box::new(SymbolicValue::Symbol("y".to_string())),
        );
        assert_eq!(CoqExporter::value_to_coq(&add), "(fadd x y)");
    }

    #[test]
    fn test_export_obligation_has_no_admitted() {
        let exporter = CoqExporter::new(
            "21888242871839275222246405745257275088548364400416034343698204186575808495617",
        );

        let obligation = ProofObligation {
            name: "sample".to_string(),
            description: "Sample obligation".to_string(),
            property: crate::formal::CircuitProperty::ConstraintSatisfied {
                constraint_id: 0,
                description: "c0".to_string(),
            },
            property_type: crate::formal::PropertyType::Soundness,
            constraints: Vec::new(),
            variables: vec!["x".to_string()],
            preconditions: vec![SymbolicConstraint::Eq(
                SymbolicValue::Symbol("x".to_string()),
                SymbolicValue::Symbol("x".to_string()),
            )],
            postconditions: vec![SymbolicConstraint::True],
        };

        let result = exporter.export_obligation(&obligation);
        assert!(result.code.contains("sample_obligation"));
        assert!(!result.code.contains("Admitted"));
    }
}
