//! Coq Proof Export
//!
//! Generates Coq proof code from ZK circuit constraints.

use super::{ProofExporter, ProofObligation, ProofResult, ProofSystem};
use crate::analysis::symbolic::{SymbolicConstraint, SymbolicValue};
use zk_core::ConstraintEquation;
use zk_core::FieldElement;

/// Coq proof exporter
pub struct CoqExporter {
    /// Field modulus
    field_modulus: String,
    /// Include standard library
    include_stdlib: bool,
}

impl CoqExporter {
    pub fn new(field_modulus: &str) -> Self {
        Self {
            field_modulus: field_modulus.to_string(),
            include_stdlib: true,
        }
    }

    /// Generate Coq header with imports
    fn generate_header(&self, module_name: &str) -> String {
        let mut header = String::new();

        header.push_str("(*\n");
        header.push_str("  Auto-generated Coq proof for ZK circuit verification\n");
        header.push_str("  Generated by ZkPatternFuzz\n");
        header.push_str("*)\n\n");

        if self.include_stdlib {
            header.push_str("Require Import Coq.ZArith.ZArith.\n");
            header.push_str("Require Import Coq.micromega.Lia.\n");
            header.push_str("Require Import Coq.Lists.List.\n");
            header.push_str("Import ListNotations.\n\n");
        }

        header.push_str(&format!("Module {}.\n\n", module_name));

        // Define the field
        header.push_str("(* BN254 scalar field *)\n");
        header.push_str(&format!(
            "Definition p : Z := {}%Z.\n\n",
            self.field_modulus
        ));

        // Define field type
        header.push_str("(* Field element type *)\n");
        header.push_str("Definition F := { x : Z | 0 <= x < p }.\n\n");

        // Field operations
        header.push_str("(* Field operations modulo p *)\n");
        header.push_str("Definition fadd (a b : Z) : Z := (a + b) mod p.\n");
        header.push_str("Definition fmul (a b : Z) : Z := (a * b) mod p.\n");
        header.push_str("Definition fsub (a b : Z) : Z := (a - b + p) mod p.\n");
        header.push_str("Definition fneg (a : Z) : Z := (p - a) mod p.\n\n");

        header
    }

    /// Generate Coq footer
    fn generate_footer(&self, module_name: &str) -> String {
        format!("\nEnd {}.\n", module_name)
    }

    /// Convert symbolic value to Coq expression
    fn value_to_coq(&self, value: &SymbolicValue) -> String {
        match value {
            SymbolicValue::Concrete(fe) => {
                format!("{}%Z", fe.to_decimal_string())
            }
            SymbolicValue::Symbol(name) => {
                // Convert to valid Coq identifier
                let clean: String = name
                    .chars()
                    .map(|c| if c.is_alphanumeric() { c } else { '_' })
                    .collect();
                clean
            }
            SymbolicValue::Add(a, b) => {
                format!("(fadd {} {})", self.value_to_coq(a), self.value_to_coq(b))
            }
            SymbolicValue::Mul(a, b) => {
                format!("(fmul {} {})", self.value_to_coq(a), self.value_to_coq(b))
            }
            SymbolicValue::Sub(a, b) => {
                format!("(fsub {} {})", self.value_to_coq(a), self.value_to_coq(b))
            }
            SymbolicValue::Neg(a) => {
                format!("(fneg {})", self.value_to_coq(a))
            }
            _ => "0%Z".to_string(),
        }
    }

    /// Convert symbolic constraint to Coq proposition
    fn constraint_to_coq(&self, constraint: &SymbolicConstraint) -> String {
        match constraint {
            SymbolicConstraint::Eq(a, b) => {
                format!("{} = {}", self.value_to_coq(a), self.value_to_coq(b))
            }
            SymbolicConstraint::Neq(a, b) => {
                format!("{} <> {}", self.value_to_coq(a), self.value_to_coq(b))
            }
            SymbolicConstraint::R1CS { a, b, c } => {
                format!(
                    "fmul {} {} = {}",
                    self.value_to_coq(a),
                    self.value_to_coq(b),
                    self.value_to_coq(c)
                )
            }
            SymbolicConstraint::Boolean(v) => {
                format!(
                    "({} = 0%Z \\/ {} = 1%Z)",
                    self.value_to_coq(v),
                    self.value_to_coq(v)
                )
            }
            SymbolicConstraint::And(c1, c2) => {
                format!(
                    "({} /\\ {})",
                    self.constraint_to_coq(c1),
                    self.constraint_to_coq(c2)
                )
            }
            SymbolicConstraint::Or(c1, c2) => {
                format!(
                    "({} \\/ {})",
                    self.constraint_to_coq(c1),
                    self.constraint_to_coq(c2)
                )
            }
            SymbolicConstraint::Not(c) => {
                format!("~({})", self.constraint_to_coq(c))
            }
            SymbolicConstraint::True => "True".to_string(),
            SymbolicConstraint::False => "False".to_string(),
            _ => "True".to_string(),
        }
    }

    /// Generate a lemma for a constraint equation
    fn equation_to_lemma(&self, eq: &ConstraintEquation, idx: usize) -> String {
        let mut lemma = String::new();

        // Comment with description
        if let Some(ref desc) = eq.description {
            lemma.push_str(&format!("(* {} *)\n", desc));
        }

        // Extract variable names
        let vars: Vec<usize> = eq
            .a_terms
            .iter()
            .chain(eq.b_terms.iter())
            .chain(eq.c_terms.iter())
            .map(|(idx, _)| *idx)
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();

        // Generate lemma signature
        lemma.push_str(&format!("Lemma constraint_{} : forall ", idx));
        for var in &vars {
            lemma.push_str(&format!("(x{} : Z) ", var));
        }

        // Add field bounds hypotheses
        lemma.push_str(",\n  ");
        for (i, var) in vars.iter().enumerate() {
            if i > 0 {
                lemma.push_str(" ->\n  ");
            }
            lemma.push_str(&format!("(0 <= x{} < p)", var));
        }

        // Generate the R1CS constraint
        let a_expr = self.linear_combination_to_coq(&eq.a_terms);
        let b_expr = self.linear_combination_to_coq(&eq.b_terms);
        let c_expr = self.linear_combination_to_coq(&eq.c_terms);

        lemma.push_str(&format!(
            " ->\n  fmul ({}) ({}) = ({}).\n",
            a_expr, b_expr, c_expr
        ));

        // Add proof skeleton with generated obligations
        lemma.push_str("Proof.\n");
        lemma.push_str("  intros.\n");
        lemma.push_str("  (* Auto-generated proof skeleton.\n");
        lemma.push_str("     Complete this proof by providing the field-arithmetic\n");
        lemma.push_str("     steps that justify the R1CS constraint. *)\n");
        lemma.push_str("  (* Obligation: show A·B = C under the given hypotheses. *)\n");
        lemma.push_str("Admitted. (* SKELETON-ONLY: replace Admitted with Qed once proved *)\n\n");

        lemma
    }

    /// Convert linear combination to Coq expression
    fn linear_combination_to_coq(&self, terms: &[(usize, FieldElement)]) -> String {
        if terms.is_empty() {
            return "0%Z".to_string();
        }

        let term_strs: Vec<String> = terms
            .iter()
            .map(|(idx, coeff)| {
                if coeff.is_one() {
                    format!("x{}", idx)
                } else {
                    format!("fmul {}%Z x{}", coeff.to_decimal_string(), idx)
                }
            })
            .collect();

        if term_strs.len() == 1 {
            term_strs[0].clone()
        } else {
            // Fold additions
            let mut result = term_strs[0].clone();
            for term in &term_strs[1..] {
                result = format!("fadd ({}) ({})", result, term);
            }
            result
        }
    }
}

impl ProofExporter for CoqExporter {
    fn system(&self) -> ProofSystem {
        ProofSystem::Coq
    }

    fn export_obligation(&self, obligation: &ProofObligation) -> ProofResult {
        let mut code = String::new();

        // Generate lemma
        code.push_str(&format!("(* {} *)\n", obligation.description));
        code.push_str(&format!("Lemma {} : forall ", obligation.name));

        // Add variables
        for var in &obligation.variables {
            code.push_str(&format!("({} : Z) ", var));
        }

        code.push_str(",\n  ");

        // Add preconditions as hypotheses
        let pre_strs: Vec<String> = obligation
            .preconditions
            .iter()
            .map(|c| self.constraint_to_coq(c))
            .collect();

        if !pre_strs.is_empty() {
            code.push_str(&pre_strs.join(" ->\n  "));
            code.push_str(" ->\n  ");
        }

        // Add postconditions as goal
        let goals: Vec<String> = obligation
            .postconditions
            .iter()
            .map(|c| self.constraint_to_coq(c))
            .collect();

        if goals.is_empty() {
            code.push_str("True");
        } else {
            code.push_str(&goals.join(" /\\ "));
        }

        code.push_str(".\n");
        code.push_str("Proof.\n");
        code.push_str("  intros.\n");
        code.push_str("  (* Auto-generated proof skeleton.\n");
        code.push_str("     Prove each postcondition from the given preconditions. *)\n");
        code.push_str("Admitted. (* SKELETON-ONLY: replace Admitted with Qed once proved *)\n");

        ProofResult {
            code,
            extension: "v",
            success: true,
            system: ProofSystem::Coq,
            dependencies: vec!["Coq.ZArith.ZArith".to_string()],
            warnings: vec!["Output is skeleton-only: all lemmas use Admitted and must be completed manually.".to_string()],
        }
    }

    fn export_module(&self, name: &str, obligations: &[ProofObligation]) -> ProofResult {
        let mut code = self.generate_header(name);

        for obligation in obligations {
            let result = self.export_obligation(obligation);
            code.push_str(&result.code);
            code.push('\n');
        }

        code.push_str(&self.generate_footer(name));

        ProofResult {
            code,
            extension: "v",
            success: true,
            system: ProofSystem::Coq,
            dependencies: vec!["Coq.ZArith.ZArith".to_string()],
            warnings: vec![],
        }
    }

    fn export_circuit(&self, name: &str, constraints: &[ConstraintEquation]) -> ProofResult {
        let mut code = self.generate_header(name);

        code.push_str("(* Circuit constraint lemmas *)\n\n");

        for (i, eq) in constraints.iter().enumerate() {
            code.push_str(&self.equation_to_lemma(eq, i));
        }

        // Generate main soundness theorem
        code.push_str("(* Main soundness theorem *)\n");
        code.push_str(&format!(
            "Theorem {}_soundness : forall (witness : nat -> Z),\n",
            name.to_lowercase()
        ));
        code.push_str("  (forall i, 0 <= witness i < p) ->\n");
        code.push_str("  (forall i, constraint_satisfied witness i) ->\n");
        code.push_str("  circuit_valid witness.\n");
        code.push_str("Proof.\n");
        code.push_str("  intros.\n");
        code.push_str("  (* Auto-generated soundness skeleton.\n");
        code.push_str("     Prove that any witness satisfying all constraints is valid. *)\n");
        code.push_str("Admitted. (* SKELETON-ONLY: replace Admitted with Qed once proved *)\n");

        code.push_str(&self.generate_footer(name));

        ProofResult {
            code,
            extension: "v",
            success: true,
            system: ProofSystem::Coq,
            dependencies: vec!["Coq.ZArith.ZArith".to_string()],
            warnings: vec!["Output is skeleton-only: all lemmas use Admitted and must be completed manually.".to_string()],
        }
    }

    fn generate_skeleton(&self, obligation: &ProofObligation) -> String {
        format!(
            "(* Proof skeleton for {} *)\n(* Goal: {} *)\nAdmitted.",
            obligation.name, obligation.description
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_coq_exporter_creation() {
        let exporter = CoqExporter::new(
            "21888242871839275222246405745257275088548364400416034343698204186575808495617",
        );
        assert_eq!(exporter.system(), ProofSystem::Coq);
    }

    #[test]
    fn test_value_to_coq() {
        let exporter = CoqExporter::new(
            "21888242871839275222246405745257275088548364400416034343698204186575808495617",
        );

        let sym = SymbolicValue::Symbol("x".to_string());
        assert_eq!(exporter.value_to_coq(&sym), "x");

        let add = SymbolicValue::Add(
            Box::new(SymbolicValue::Symbol("x".to_string())),
            Box::new(SymbolicValue::Symbol("y".to_string())),
        );
        assert_eq!(exporter.value_to_coq(&add), "(fadd x y)");
    }
}
