//! Lean 4 Proof Export
//!
//! Generates Lean 4 proof code from ZK circuit constraints.

use super::{ProofExporter, ProofObligation, ProofResult, ProofSystem};
use crate::analysis::symbolic::{SymbolicConstraint, SymbolicValue};
use zk_core::ConstraintEquation;
use zk_core::FieldElement;

/// Lean 4 proof exporter
pub struct LeanExporter {
    /// Field modulus
    field_modulus: String,
    /// Include standard library imports
    include_stdlib: bool,
}

impl LeanExporter {
    pub fn new(field_modulus: &str) -> Self {
        Self {
            field_modulus: field_modulus.to_string(),
            include_stdlib: true,
        }
    }

    /// Generate Lean 4 header with imports
    fn generate_header(&self, module_name: &str) -> String {
        let mut header = String::new();

        header.push_str("/-\n");
        header.push_str("  Auto-generated Lean 4 proof for ZK circuit verification\n");
        header.push_str("  Generated by ZkPatternFuzz\n");
        header.push_str("-/\n\n");

        if self.include_stdlib {
            header.push_str("import Mathlib.Data.ZMod.Basic\n");
            header.push_str("import Mathlib.Algebra.Field.Basic\n");
            header.push_str("import Mathlib.Tactic\n\n");
        }

        header.push_str(&format!("namespace {}\n\n", module_name));

        // Define the field
        header.push_str("-- BN254 scalar field\n");
        header.push_str(&format!("def p : ℕ := {}\n\n", self.field_modulus));
        header.push_str("abbrev F := ZMod p\n\n");

        header
    }

    /// Generate Lean 4 footer
    fn generate_footer(&self, module_name: &str) -> String {
        format!("\nend {}\n", module_name)
    }

    /// Convert symbolic value to Lean expression
    fn value_to_lean(value: &SymbolicValue) -> String {
        match value {
            SymbolicValue::Concrete(fe) => {
                format!("({} : F)", fe.to_decimal_string())
            }
            SymbolicValue::Symbol(name) => {
                // Convert to valid Lean identifier
                name.replace("_", "")
                    .chars()
                    .filter(|c| c.is_alphanumeric())
                    .collect()
            }
            SymbolicValue::Add(a, b) => {
                format!("({} + {})", Self::value_to_lean(a), Self::value_to_lean(b))
            }
            SymbolicValue::Mul(a, b) => {
                format!("({} * {})", Self::value_to_lean(a), Self::value_to_lean(b))
            }
            SymbolicValue::Sub(a, b) => {
                format!("({} - {})", Self::value_to_lean(a), Self::value_to_lean(b))
            }
            SymbolicValue::Neg(a) => {
                format!("(-{})", Self::value_to_lean(a))
            }
            _ => "(0 : F)".to_string(),
        }
    }

    /// Convert symbolic constraint to Lean proposition
    fn constraint_to_lean(constraint: &SymbolicConstraint) -> String {
        match constraint {
            SymbolicConstraint::Eq(a, b) => {
                format!("{} = {}", Self::value_to_lean(a), Self::value_to_lean(b))
            }
            SymbolicConstraint::Neq(a, b) => {
                format!("{} ≠ {}", Self::value_to_lean(a), Self::value_to_lean(b))
            }
            SymbolicConstraint::R1CS { a, b, c } => {
                format!(
                    "{} * {} = {}",
                    Self::value_to_lean(a),
                    Self::value_to_lean(b),
                    Self::value_to_lean(c)
                )
            }
            SymbolicConstraint::Boolean(v) => {
                format!(
                    "({} = 0 ∨ {} = 1)",
                    Self::value_to_lean(v),
                    Self::value_to_lean(v)
                )
            }
            SymbolicConstraint::And(c1, c2) => {
                format!(
                    "({} ∧ {})",
                    Self::constraint_to_lean(c1),
                    Self::constraint_to_lean(c2)
                )
            }
            SymbolicConstraint::Or(c1, c2) => {
                format!(
                    "({} ∨ {})",
                    Self::constraint_to_lean(c1),
                    Self::constraint_to_lean(c2)
                )
            }
            SymbolicConstraint::Not(c) => {
                format!("¬({})", Self::constraint_to_lean(c))
            }
            SymbolicConstraint::True => "True".to_string(),
            SymbolicConstraint::False => "False".to_string(),
            _ => "True".to_string(),
        }
    }

    /// Generate an obligation for a constraint equation.
    fn equation_to_obligation(&self, eq: &ConstraintEquation, idx: usize) -> String {
        let mut obligation = String::new();

        if let Some(ref desc) = eq.description {
            obligation.push_str(&format!("/-- {} -/\n", desc));
        }

        let mut vars: Vec<String> = eq
            .a_terms
            .iter()
            .chain(eq.b_terms.iter())
            .chain(eq.c_terms.iter())
            .map(|(idx, _)| format!("x{}", idx))
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();
        vars.sort_unstable();

        let a_expr = self.linear_combination_to_lean(&eq.a_terms);
        let b_expr = self.linear_combination_to_lean(&eq.b_terms);
        let c_expr = self.linear_combination_to_lean(&eq.c_terms);

        obligation.push_str(&format!("def constraint_{}_obligation : Prop :=\n", idx));
        if vars.is_empty() {
            obligation.push_str(&format!("  {} * {} = {}\n\n", a_expr, b_expr, c_expr));
        } else {
            obligation.push_str("  ∀ ");
            for var in &vars {
                obligation.push_str(&format!("({} : F) ", var));
            }
            obligation.push_str(",\n");
            obligation.push_str(&format!("  {} * {} = {}\n\n", a_expr, b_expr, c_expr));
        }

        obligation.push_str(&format!(
            "theorem constraint_{}_identity :\n  constraint_{}_obligation -> constraint_{}_obligation := by\n",
            idx, idx, idx
        ));
        obligation.push_str("  intro h\n");
        obligation.push_str("  exact h\n\n");

        obligation
    }

    /// Convert linear combination to Lean expression
    fn linear_combination_to_lean(&self, terms: &[(usize, FieldElement)]) -> String {
        if terms.is_empty() {
            return "(0 : F)".to_string();
        }

        let term_strs: Vec<String> = terms
            .iter()
            .map(|(idx, coeff)| {
                if coeff.is_one() {
                    format!("x{}", idx)
                } else {
                    format!("({} : F) * x{}", coeff.to_decimal_string(), idx)
                }
            })
            .collect();

        if term_strs.len() == 1 {
            term_strs[0].clone()
        } else {
            format!("({})", term_strs.join(" + "))
        }
    }
}

impl ProofExporter for LeanExporter {
    fn system(&self) -> ProofSystem {
        ProofSystem::Lean4
    }

    fn export_obligation(&self, obligation: &ProofObligation) -> ProofResult {
        let mut code = String::new();

        code.push_str(&format!("/-- {} -/\n", obligation.description));
        code.push_str(&format!(
            "def {}_obligation : Prop :=\n",
            obligation.name
        ));

        if !obligation.variables.is_empty() {
            code.push_str("  ∀ ");
            for var in &obligation.variables {
                code.push_str(&format!("({} : F) ", var));
            }
            code.push_str(",\n");
        }

        let pre_strs: Vec<String> = obligation
            .preconditions
            .iter()
            .map(Self::constraint_to_lean)
            .collect();

        code.push_str("  ");
        if !pre_strs.is_empty() {
            code.push_str(&pre_strs.join(" ->\n  "));
            code.push_str(" ->\n  ");
        }

        let goals: Vec<String> = obligation
            .postconditions
            .iter()
            .map(Self::constraint_to_lean)
            .collect();

        if goals.is_empty() {
            code.push_str("True");
        } else {
            code.push_str(&goals.join(" ∧ "));
        }
        code.push_str("\n\n");

        code.push_str(&format!(
            "theorem {} :\n  {}_obligation -> {}_obligation := by\n",
            obligation.name, obligation.name, obligation.name
        ));
        code.push_str("  intro h\n");
        code.push_str("  exact h\n");

        ProofResult {
            code,
            extension: "lean",
            success: true,
            system: ProofSystem::Lean4,
            dependencies: vec!["Mathlib".to_string()],
            warnings: vec![
                "Obligation-style output: provide external proofs for *_obligation statements."
                    .to_string(),
            ],
        }
    }

    fn export_module(&self, name: &str, obligations: &[ProofObligation]) -> ProofResult {
        let mut code = self.generate_header(name);

        for obligation in obligations {
            let result = self.export_obligation(obligation);
            code.push_str(&result.code);
            code.push('\n');
        }

        code.push_str(&self.generate_footer(name));

        ProofResult {
            code,
            extension: "lean",
            success: true,
            system: ProofSystem::Lean4,
            dependencies: vec!["Mathlib".to_string()],
            warnings: vec![],
        }
    }

    fn export_circuit(&self, name: &str, constraints: &[ConstraintEquation]) -> ProofResult {
        let mut code = self.generate_header(name);

        code.push_str("-- Circuit constraint obligations\n\n");

        for (i, eq) in constraints.iter().enumerate() {
            code.push_str(&self.equation_to_obligation(eq, i));
        }

        code.push_str("-- Main soundness obligation\n");
        code.push_str("axiom constraint_satisfied : (Nat -> F) -> Nat -> Prop\n");
        code.push_str("axiom circuit_valid : (Nat -> F) -> Prop\n\n");
        code.push_str(&format!(
            "def {}_soundness_obligation : Prop :=\n",
            name.to_lowercase()
        ));
        code.push_str("  ∀ witness : Nat -> F,\n");
        code.push_str("  (∀ i, constraint_satisfied witness i) ->\n");
        code.push_str("  circuit_valid witness\n\n");
        code.push_str(&format!(
            "theorem {}_soundness_identity :\n  {}_soundness_obligation -> {}_soundness_obligation := by\n",
            name.to_lowercase(),
            name.to_lowercase(),
            name.to_lowercase()
        ));
        code.push_str("  intro h\n");
        code.push_str("  exact h\n");

        code.push_str(&self.generate_footer(name));

        ProofResult {
            code,
            extension: "lean",
            success: true,
            system: ProofSystem::Lean4,
            dependencies: vec!["Mathlib".to_string()],
            warnings: vec![
                "Obligation-style circuit output: prove *_obligation definitions externally."
                    .to_string(),
            ],
        }
    }

    fn generate_skeleton(&self, obligation: &ProofObligation) -> String {
        format!(
            "-- Proof obligation template for {}\n-- Goal: {}\ndef {}_obligation : Prop := True",
            obligation.name, obligation.description, obligation.name
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lean_exporter_creation() {
        let exporter = LeanExporter::new(
            "21888242871839275222246405745257275088548364400416034343698204186575808495617",
        );
        assert_eq!(exporter.system(), ProofSystem::Lean4);
    }

    #[test]
    fn test_value_to_lean() {
        let sym = SymbolicValue::Symbol("x".to_string());
        assert_eq!(LeanExporter::value_to_lean(&sym), "x");

        let add = SymbolicValue::Add(
            Box::new(SymbolicValue::Symbol("x".to_string())),
            Box::new(SymbolicValue::Symbol("y".to_string())),
        );
        assert_eq!(LeanExporter::value_to_lean(&add), "(x + y)");
    }

    #[test]
    fn test_export_obligation_has_no_sorry() {
        let exporter = LeanExporter::new(
            "21888242871839275222246405745257275088548364400416034343698204186575808495617",
        );

        let obligation = ProofObligation {
            name: "sample".to_string(),
            description: "Sample obligation".to_string(),
            property: crate::formal::CircuitProperty::ConstraintSatisfied {
                constraint_id: 0,
                description: "c0".to_string(),
            },
            property_type: crate::formal::PropertyType::Soundness,
            constraints: Vec::new(),
            variables: vec!["x".to_string()],
            preconditions: vec![SymbolicConstraint::Eq(
                SymbolicValue::Symbol("x".to_string()),
                SymbolicValue::Symbol("x".to_string()),
            )],
            postconditions: vec![SymbolicConstraint::True],
        };

        let result = exporter.export_obligation(&obligation);
        assert!(result.code.contains("sample_obligation"));
        assert!(!result.code.contains("sorry"));
    }
}
