//! Lean 4 Proof Export
//!
//! Generates Lean 4 proof code from ZK circuit constraints.

use super::{ProofExporter, ProofObligation, ProofResult, ProofSystem};
use crate::analysis::symbolic::{SymbolicConstraint, SymbolicValue};
use zk_core::ConstraintEquation;
use zk_core::FieldElement;

/// Lean 4 proof exporter
pub struct LeanExporter {
    /// Field modulus
    field_modulus: String,
    /// Include standard library imports
    include_stdlib: bool,
}

impl LeanExporter {
    pub fn new(field_modulus: &str) -> Self {
        Self {
            field_modulus: field_modulus.to_string(),
            include_stdlib: true,
        }
    }

    /// Generate Lean 4 header with imports
    fn generate_header(&self, module_name: &str) -> String {
        let mut header = String::new();

        header.push_str("/-\n");
        header.push_str("  Auto-generated Lean 4 proof for ZK circuit verification\n");
        header.push_str("  Generated by ZkPatternFuzz\n");
        header.push_str("-/\n\n");

        if self.include_stdlib {
            header.push_str("import Mathlib.Data.ZMod.Basic\n");
            header.push_str("import Mathlib.Algebra.Field.Basic\n");
            header.push_str("import Mathlib.Tactic\n\n");
        }

        header.push_str(&format!("namespace {}\n\n", module_name));

        // Define the field
        header.push_str("-- BN254 scalar field\n");
        header.push_str(&format!("def p : ℕ := {}\n\n", self.field_modulus));
        header.push_str("abbrev F := ZMod p\n\n");

        header
    }

    /// Generate Lean 4 footer
    fn generate_footer(&self, module_name: &str) -> String {
        format!("\nend {}\n", module_name)
    }

    /// Convert symbolic value to Lean expression
    fn value_to_lean(&self, value: &SymbolicValue) -> String {
        match value {
            SymbolicValue::Concrete(fe) => {
                format!("({} : F)", fe.to_decimal_string())
            }
            SymbolicValue::Symbol(name) => {
                // Convert to valid Lean identifier
                name.replace("_", "")
                    .chars()
                    .filter(|c| c.is_alphanumeric())
                    .collect()
            }
            SymbolicValue::Add(a, b) => {
                format!("({} + {})", self.value_to_lean(a), self.value_to_lean(b))
            }
            SymbolicValue::Mul(a, b) => {
                format!("({} * {})", self.value_to_lean(a), self.value_to_lean(b))
            }
            SymbolicValue::Sub(a, b) => {
                format!("({} - {})", self.value_to_lean(a), self.value_to_lean(b))
            }
            SymbolicValue::Neg(a) => {
                format!("(-{})", self.value_to_lean(a))
            }
            _ => "sorry".to_string(),
        }
    }

    /// Convert symbolic constraint to Lean proposition
    fn constraint_to_lean(&self, constraint: &SymbolicConstraint) -> String {
        match constraint {
            SymbolicConstraint::Eq(a, b) => {
                format!("{} = {}", self.value_to_lean(a), self.value_to_lean(b))
            }
            SymbolicConstraint::Neq(a, b) => {
                format!("{} ≠ {}", self.value_to_lean(a), self.value_to_lean(b))
            }
            SymbolicConstraint::R1CS { a, b, c } => {
                format!(
                    "{} * {} = {}",
                    self.value_to_lean(a),
                    self.value_to_lean(b),
                    self.value_to_lean(c)
                )
            }
            SymbolicConstraint::Boolean(v) => {
                format!(
                    "({} = 0 ∨ {} = 1)",
                    self.value_to_lean(v),
                    self.value_to_lean(v)
                )
            }
            SymbolicConstraint::And(c1, c2) => {
                format!(
                    "({} ∧ {})",
                    self.constraint_to_lean(c1),
                    self.constraint_to_lean(c2)
                )
            }
            SymbolicConstraint::Or(c1, c2) => {
                format!(
                    "({} ∨ {})",
                    self.constraint_to_lean(c1),
                    self.constraint_to_lean(c2)
                )
            }
            SymbolicConstraint::Not(c) => {
                format!("¬({})", self.constraint_to_lean(c))
            }
            SymbolicConstraint::True => "True".to_string(),
            SymbolicConstraint::False => "False".to_string(),
            _ => "True".to_string(),
        }
    }

    /// Generate a theorem for a constraint equation
    fn equation_to_theorem(&self, eq: &ConstraintEquation, idx: usize) -> String {
        let mut theorem = String::new();

        // Comment with description
        if let Some(ref desc) = eq.description {
            theorem.push_str(&format!("/-- {} -/\n", desc));
        }

        // Extract variable names
        let vars: Vec<String> = eq
            .a_terms
            .iter()
            .chain(eq.b_terms.iter())
            .chain(eq.c_terms.iter())
            .map(|(idx, _)| format!("x{}", idx))
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();

        // Generate theorem signature
        theorem.push_str(&format!("theorem constraint_{} ", idx));
        for var in &vars {
            theorem.push_str(&format!("({} : F) ", var));
        }

        // Generate the R1CS constraint: sum(a_i * x_i) * sum(b_i * x_i) = sum(c_i * x_i)
        let a_expr = self.linear_combination_to_lean(&eq.a_terms);
        let b_expr = self.linear_combination_to_lean(&eq.b_terms);
        let c_expr = self.linear_combination_to_lean(&eq.c_terms);

        theorem.push_str(&format!(
            ":\n    {} * {} = {} := by\n",
            a_expr, b_expr, c_expr
        ));

        // Add proof skeleton with generated obligation
        theorem.push_str("  -- Auto-generated proof skeleton.\n");
        theorem.push_str("  -- Obligation: show A * B = C under the field axioms.\n");
        theorem.push_str("  sorry -- SKELETON-ONLY: replace sorry with a real proof\n\n");

        theorem
    }

    /// Convert linear combination to Lean expression
    fn linear_combination_to_lean(&self, terms: &[(usize, FieldElement)]) -> String {
        if terms.is_empty() {
            return "(0 : F)".to_string();
        }

        let term_strs: Vec<String> = terms
            .iter()
            .map(|(idx, coeff)| {
                if coeff.is_one() {
                    format!("x{}", idx)
                } else {
                    format!("({} : F) * x{}", coeff.to_decimal_string(), idx)
                }
            })
            .collect();

        if term_strs.len() == 1 {
            term_strs[0].clone()
        } else {
            format!("({})", term_strs.join(" + "))
        }
    }
}

impl ProofExporter for LeanExporter {
    fn system(&self) -> ProofSystem {
        ProofSystem::Lean4
    }

    fn export_obligation(&self, obligation: &ProofObligation) -> ProofResult {
        let mut code = String::new();

        // Generate theorem
        code.push_str(&format!("/-- {} -/\n", obligation.description));
        code.push_str(&format!("theorem {} ", obligation.name));

        // Add variables
        for var in &obligation.variables {
            code.push_str(&format!("({} : F) ", var));
        }

        // Add preconditions as hypotheses
        for (i, pre) in obligation.preconditions.iter().enumerate() {
            code.push_str(&format!("(h{} : {}) ", i, self.constraint_to_lean(pre)));
        }

        code.push_str(":\n    ");

        // Add postconditions as goal
        let goals: Vec<String> = obligation
            .postconditions
            .iter()
            .map(|c| self.constraint_to_lean(c))
            .collect();

        if goals.is_empty() {
            code.push_str("True");
        } else {
            code.push_str(&goals.join(" ∧ "));
        }

        code.push_str(" := by\n");
        code.push_str("  -- Auto-generated proof skeleton.\n");
        code.push_str("  -- Prove each postcondition from the given hypotheses.\n");
        code.push_str("  sorry -- SKELETON-ONLY: replace sorry with a real proof\n");

        ProofResult {
            code,
            extension: "lean",
            success: true,
            system: ProofSystem::Lean4,
            dependencies: vec!["Mathlib".to_string()],
            warnings: vec!["Output is skeleton-only: all theorems use sorry and must be completed manually.".to_string()],
        }
    }

    fn export_module(&self, name: &str, obligations: &[ProofObligation]) -> ProofResult {
        let mut code = self.generate_header(name);

        for obligation in obligations {
            let result = self.export_obligation(obligation);
            code.push_str(&result.code);
            code.push('\n');
        }

        code.push_str(&self.generate_footer(name));

        ProofResult {
            code,
            extension: "lean",
            success: true,
            system: ProofSystem::Lean4,
            dependencies: vec!["Mathlib".to_string()],
            warnings: vec![],
        }
    }

    fn export_circuit(&self, name: &str, constraints: &[ConstraintEquation]) -> ProofResult {
        let mut code = self.generate_header(name);

        code.push_str("-- Circuit constraint theorems\n\n");

        for (i, eq) in constraints.iter().enumerate() {
            code.push_str(&self.equation_to_theorem(eq, i));
        }

        // Generate main soundness theorem
        code.push_str("-- Main soundness theorem\n");
        code.push_str(&format!(
            "theorem {}_soundness : ∀ witness : Fin {} → F,\n",
            name.to_lowercase(),
            constraints.len()
        ));
        code.push_str("  (∀ i, constraint_satisfied witness i) →\n");
        code.push_str("  circuit_valid witness := by\n");
        code.push_str("  -- Auto-generated soundness skeleton.\n");
        code.push_str("  -- Prove that any witness satisfying all constraints is valid.\n");
        code.push_str("  sorry -- SKELETON-ONLY: replace sorry with a real proof\n");

        code.push_str(&self.generate_footer(name));

        ProofResult {
            code,
            extension: "lean",
            success: true,
            system: ProofSystem::Lean4,
            dependencies: vec!["Mathlib".to_string()],
            warnings: vec!["Output is skeleton-only: all theorems use sorry and must be completed manually.".to_string()],
        }
    }

    fn generate_skeleton(&self, obligation: &ProofObligation) -> String {
        format!(
            "-- Proof skeleton for {}\n-- Goal: {}\nsorry",
            obligation.name, obligation.description
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lean_exporter_creation() {
        let exporter = LeanExporter::new(
            "21888242871839275222246405745257275088548364400416034343698204186575808495617",
        );
        assert_eq!(exporter.system(), ProofSystem::Lean4);
    }

    #[test]
    fn test_value_to_lean() {
        let exporter = LeanExporter::new(
            "21888242871839275222246405745257275088548364400416034343698204186575808495617",
        );

        let sym = SymbolicValue::Symbol("x".to_string());
        assert_eq!(exporter.value_to_lean(&sym), "x");

        let add = SymbolicValue::Add(
            Box::new(SymbolicValue::Symbol("x".to_string())),
            Box::new(SymbolicValue::Symbol("y".to_string())),
        );
        assert_eq!(exporter.value_to_lean(&add), "(x + y)");
    }
}
