//! Proof-of-Concept Generator
//!
//! Generates runnable exploit reproduction scripts from findings.
//! Supports multiple output formats:
//! - Shell scripts for CLI reproduction
//! - JavaScript for browser/Node.js
//! - Rust test cases
//! - Python scripts
//!
//! # Example
//!
//! ```rust,ignore
//! use zk_fuzzer::reporting::poc_generator::{PoCGenerator, PoCFormat};
//!
//! let generator = PoCGenerator::new();
//! let finding = /* ... */;
//!
//! let script = generator.generate(&finding, PoCFormat::Shell)?;
//! println!("{}", script);
//! ```

use crate::config::Framework;
use zk_core::{FieldElement, Finding};
use serde::Serialize;
use std::fmt::Write;

/// Output format for PoC scripts
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PoCFormat {
    /// Bash shell script
    Shell,
    /// JavaScript (Node.js / snarkjs)
    JavaScript,
    /// Rust test case
    Rust,
    /// Python script
    Python,
    /// JSON witness file
    Json,
}

/// Configuration for PoC generation
#[derive(Debug, Clone)]
pub struct PoCGeneratorConfig {
    /// Include comments explaining the exploit
    pub include_comments: bool,
    /// Include setup/installation instructions
    pub include_setup: bool,
    /// Include verification step
    pub include_verification: bool,
    /// Circuit path for imports
    pub circuit_path: Option<String>,
    /// Main component name
    pub main_component: Option<String>,
    /// Target framework
    pub framework: Framework,
}

impl Default for PoCGeneratorConfig {
    fn default() -> Self {
        Self {
            include_comments: true,
            include_setup: true,
            include_verification: true,
            circuit_path: None,
            main_component: None,
            framework: Framework::Circom,
        }
    }
}

/// PoC Generator
pub struct PoCGenerator {
    config: PoCGeneratorConfig,
}

impl PoCGenerator {
    pub fn new() -> Self {
        Self {
            config: PoCGeneratorConfig::default(),
        }
    }

    pub fn with_config(config: PoCGeneratorConfig) -> Self {
        Self { config }
    }

    /// Generate PoC script for a finding
    pub fn generate(&self, finding: &Finding, format: PoCFormat) -> anyhow::Result<String> {
        match format {
            PoCFormat::Shell => self.generate_shell(finding),
            PoCFormat::JavaScript => self.generate_javascript(finding),
            PoCFormat::Rust => self.generate_rust(finding),
            PoCFormat::Python => self.generate_python(finding),
            PoCFormat::Json => self.generate_json(finding),
        }
    }

    /// Generate shell script PoC
    fn generate_shell(&self, finding: &Finding) -> anyhow::Result<String> {
        let mut script = String::new();

        writeln!(script, "#!/bin/bash")?;
        writeln!(script, "# ZkPatternFuzz Proof of Concept")?;
        writeln!(script, "# Attack Type: {:?}", finding.attack_type)?;
        writeln!(script, "# Severity: {:?}", finding.severity)?;
        writeln!(script, "# Description: {}", finding.description)?;
        writeln!(script, "#")?;
        writeln!(script, "# Generated by ZkPatternFuzz")?;
        writeln!(script, "")?;
        writeln!(script, "set -e")?;
        writeln!(script, "")?;

        if self.config.include_setup {
            writeln!(script, "# Setup")?;
            writeln!(script, "CIRCUIT_PATH=\"{}\"", self.config.circuit_path.as_deref().unwrap_or("./circuit.circom"))?;
            writeln!(script, "PTAU_PATH=\"./powersOfTau28_hez_final_10.ptau\"")?;
            writeln!(script, "")?;
        }

        // Write witness A
        writeln!(script, "# Witness A (exploiting input)")?;
        writeln!(script, "cat > input_a.json << 'EOF'")?;
        writeln!(script, "{}", self.witness_to_json(&finding.poc.witness_a)?)?;
        writeln!(script, "EOF")?;
        writeln!(script, "")?;

        // Write witness B if present (for underconstrained)
        if let Some(ref witness_b) = finding.poc.witness_b {
            writeln!(script, "# Witness B (alternative valid witness)")?;
            writeln!(script, "cat > input_b.json << 'EOF'")?;
            writeln!(script, "{}", self.witness_to_json(witness_b)?)?;
            writeln!(script, "EOF")?;
            writeln!(script, "")?;
        }

        if self.config.include_verification {
            writeln!(script, "# Compile and generate proofs")?;
            writeln!(script, "echo \"Compiling circuit...\"")?;
            writeln!(script, "circom \"$CIRCUIT_PATH\" --r1cs --wasm --sym")?;
            writeln!(script, "")?;

            writeln!(script, "echo \"Generating proof for Witness A...\"")?;
            writeln!(script, "snarkjs groth16 setup circuit.r1cs \"$PTAU_PATH\" circuit_0000.zkey")?;
            writeln!(script, "snarkjs groth16 prove circuit_0000.zkey circuit_js/circuit.wasm input_a.json proof_a.json public_a.json")?;
            writeln!(script, "")?;

            if finding.poc.witness_b.is_some() {
                writeln!(script, "echo \"Generating proof for Witness B...\"")?;
                writeln!(script, "snarkjs groth16 prove circuit_0000.zkey circuit_js/circuit.wasm input_b.json proof_b.json public_b.json")?;
                writeln!(script, "")?;

                writeln!(script, "# Verify both proofs produce same public outputs")?;
                writeln!(script, "echo \"Comparing public outputs...\"")?;
                writeln!(script, "if diff public_a.json public_b.json > /dev/null; then")?;
                writeln!(script, "    echo \"[VULNERABILITY CONFIRMED] Same public output from different witnesses!\"")?;
                writeln!(script, "    echo \"This confirms the circuit is underconstrained.\"")?;
                writeln!(script, "else")?;
                writeln!(script, "    echo \"Public outputs differ (expected if fix applied)\"")?;
                writeln!(script, "fi")?;
            } else {
                writeln!(script, "# Verify proof")?;
                writeln!(script, "snarkjs groth16 verify verification_key.json public_a.json proof_a.json")?;
                writeln!(script, "echo \"[VULNERABILITY DEMONSTRATED] Proof verified for malicious input\"")?;
            }
        }

        writeln!(script, "")?;
        writeln!(script, "echo \"PoC execution complete\"")?;

        Ok(script)
    }

    /// Generate JavaScript PoC
    fn generate_javascript(&self, finding: &Finding) -> anyhow::Result<String> {
        let mut script = String::new();

        writeln!(script, "/**")?;
        writeln!(script, " * ZkPatternFuzz Proof of Concept")?;
        writeln!(script, " * Attack Type: {:?}", finding.attack_type)?;
        writeln!(script, " * Severity: {:?}", finding.severity)?;
        writeln!(script, " * Description: {}", finding.description)?;
        writeln!(script, " */")?;
        writeln!(script, "")?;

        writeln!(script, "const snarkjs = require(\"snarkjs\");")?;
        writeln!(script, "const fs = require(\"fs\");")?;
        writeln!(script, "")?;

        writeln!(script, "async function exploitDemo() {{")?;
        writeln!(script, "    console.log(\"=== ZkPatternFuzz PoC ===\");")?;
        writeln!(script, "    console.log(\"Attack: {:?}\");", finding.attack_type)?;
        writeln!(script, "    console.log(\"\");")?;
        writeln!(script, "")?;

        // Witness A
        writeln!(script, "    // Witness A - Exploiting input")?;
        writeln!(script, "    const witnessA = {{}};")?;
        for (i, fe) in finding.poc.witness_a.iter().enumerate() {
            writeln!(script, "    witnessA[\"input_{}\"] = \"{}\";", i, fe.to_hex())?;
        }
        writeln!(script, "")?;

        // Witness B if present
        if let Some(ref witness_b) = finding.poc.witness_b {
            writeln!(script, "    // Witness B - Alternative valid witness")?;
            writeln!(script, "    const witnessB = {{}};")?;
            for (i, fe) in witness_b.iter().enumerate() {
                writeln!(script, "    witnessB[\"input_{}\"] = \"{}\";", i, fe.to_hex())?;
            }
            writeln!(script, "")?;
        }

        writeln!(script, "    const circuitWasm = \"{}circuit_js/circuit.wasm\";",
                 self.config.circuit_path.as_deref().unwrap_or("./"))?;
        writeln!(script, "    const zkey = \"circuit_0000.zkey\";")?;
        writeln!(script, "")?;

        writeln!(script, "    try {{")?;
        writeln!(script, "        console.log(\"Generating proof for Witness A...\");")?;
        writeln!(script, "        const {{ proof: proofA, publicSignals: pubA }} = await snarkjs.groth16.fullProve(")?;
        writeln!(script, "            witnessA, circuitWasm, zkey")?;
        writeln!(script, "        );")?;
        writeln!(script, "        console.log(\"Public outputs A:\", pubA);")?;
        writeln!(script, "")?;

        if finding.poc.witness_b.is_some() {
            writeln!(script, "        console.log(\"Generating proof for Witness B...\");")?;
            writeln!(script, "        const {{ proof: proofB, publicSignals: pubB }} = await snarkjs.groth16.fullProve(")?;
            writeln!(script, "            witnessB, circuitWasm, zkey")?;
            writeln!(script, "        );")?;
            writeln!(script, "        console.log(\"Public outputs B:\", pubB);")?;
            writeln!(script, "")?;
            writeln!(script, "        // Check if outputs match (vulnerability confirmation)")?;
            writeln!(script, "        if (JSON.stringify(pubA) === JSON.stringify(pubB)) {{")?;
            writeln!(script, "            console.log(\"\\n[VULNERABILITY CONFIRMED]\");")?;
            writeln!(script, "            console.log(\"Different witnesses produce identical public outputs!\");")?;
            writeln!(script, "            console.log(\"Circuit is underconstrained.\");")?;
            writeln!(script, "        }} else {{")?;
            writeln!(script, "            console.log(\"\\nOutputs differ (vulnerability may be fixed)\");")?;
            writeln!(script, "        }}")?;
        } else {
            writeln!(script, "        console.log(\"\\n[VULNERABILITY DEMONSTRATED]\");")?;
            writeln!(script, "        console.log(\"Malicious input accepted by circuit\");")?;
        }

        writeln!(script, "    }} catch (error) {{")?;
        writeln!(script, "        console.error(\"Error:\", error.message);")?;
        writeln!(script, "    }}")?;
        writeln!(script, "}}")?;
        writeln!(script, "")?;
        writeln!(script, "exploitDemo();")?;

        Ok(script)
    }

    /// Generate Rust test case
    fn generate_rust(&self, finding: &Finding) -> anyhow::Result<String> {
        let mut script = String::new();

        writeln!(script, "//! ZkPatternFuzz Proof of Concept")?;
        writeln!(script, "//! Attack Type: {:?}", finding.attack_type)?;
        writeln!(script, "//! Severity: {:?}", finding.severity)?;
        writeln!(script, "//! Description: {}", finding.description)?;
        writeln!(script, "")?;
        writeln!(script, "#[cfg(test)]")?;
        writeln!(script, "mod poc_tests {{")?;
        writeln!(script, "    use super::*;")?;
        writeln!(script, "")?;

        let test_name = format!("test_poc_{:?}", finding.attack_type)
            .to_lowercase()
            .replace(" ", "_");

        writeln!(script, "    #[test]")?;
        writeln!(script, "    fn {}() {{", test_name)?;
        writeln!(script, "        // Witness A - Exploiting input")?;
        writeln!(script, "        let witness_a: Vec<FieldElement> = vec![")?;
        for fe in &finding.poc.witness_a {
            writeln!(script, "            FieldElement::from_hex(\"{}\").unwrap(),", fe.to_hex())?;
        }
        writeln!(script, "        ];")?;
        writeln!(script, "")?;

        if let Some(ref witness_b) = finding.poc.witness_b {
            writeln!(script, "        // Witness B - Alternative valid witness")?;
            writeln!(script, "        let witness_b: Vec<FieldElement> = vec![")?;
            for fe in witness_b {
                writeln!(script, "            FieldElement::from_hex(\"{}\").unwrap(),", fe.to_hex())?;
            }
            writeln!(script, "        ];")?;
            writeln!(script, "")?;

            writeln!(script, "        // Execute both witnesses")?;
            writeln!(script, "        let output_a = executor.execute(&witness_a).unwrap();")?;
            writeln!(script, "        let output_b = executor.execute(&witness_b).unwrap();")?;
            writeln!(script, "")?;
            writeln!(script, "        // Vulnerability: same output from different inputs")?;
            writeln!(script, "        assert_eq!(")?;
            writeln!(script, "            output_a.public_outputs,")?;
            writeln!(script, "            output_b.public_outputs,")?;
            writeln!(script, "            \"[VULNERABILITY CONFIRMED] Underconstrained circuit\"")?;
            writeln!(script, "        );")?;
        } else {
            writeln!(script, "        // Execute malicious witness")?;
            writeln!(script, "        let result = executor.execute(&witness_a);")?;
            writeln!(script, "")?;
            writeln!(script, "        // Vulnerability: malicious input accepted")?;
            writeln!(script, "        assert!(result.is_ok(), \"[VULNERABILITY CONFIRMED]\");")?;
        }

        writeln!(script, "    }}")?;
        writeln!(script, "}}")?;

        Ok(script)
    }

    /// Generate Python PoC
    fn generate_python(&self, finding: &Finding) -> anyhow::Result<String> {
        let mut script = String::new();

        writeln!(script, "#!/usr/bin/env python3")?;
        writeln!(script, "\"\"\"")?;
        writeln!(script, "ZkPatternFuzz Proof of Concept")?;
        writeln!(script, "Attack Type: {:?}", finding.attack_type)?;
        writeln!(script, "Severity: {:?}", finding.severity)?;
        writeln!(script, "Description: {}", finding.description)?;
        writeln!(script, "\"\"\"")?;
        writeln!(script, "")?;
        writeln!(script, "import json")?;
        writeln!(script, "import subprocess")?;
        writeln!(script, "from pathlib import Path")?;
        writeln!(script, "")?;

        writeln!(script, "# Witness A - Exploiting input")?;
        writeln!(script, "witness_a = {{")?;
        for (i, fe) in finding.poc.witness_a.iter().enumerate() {
            writeln!(script, "    \"input_{}\": \"{}\",", i, fe.to_hex())?;
        }
        writeln!(script, "}}")?;
        writeln!(script, "")?;

        if let Some(ref witness_b) = finding.poc.witness_b {
            writeln!(script, "# Witness B - Alternative valid witness")?;
            writeln!(script, "witness_b = {{")?;
            for (i, fe) in witness_b.iter().enumerate() {
                writeln!(script, "    \"input_{}\": \"{}\",", i, fe.to_hex())?;
            }
            writeln!(script, "}}")?;
            writeln!(script, "")?;
        }

        writeln!(script, "def main():")?;
        writeln!(script, "    print(\"=== ZkPatternFuzz PoC ===\")")?;
        writeln!(script, "    print(f\"Attack: {:?}\")", finding.attack_type)?;
        writeln!(script, "    print()")?;
        writeln!(script, "")?;

        writeln!(script, "    # Write witness files")?;
        writeln!(script, "    Path(\"input_a.json\").write_text(json.dumps(witness_a))")?;
        if finding.poc.witness_b.is_some() {
            writeln!(script, "    Path(\"input_b.json\").write_text(json.dumps(witness_b))")?;
        }
        writeln!(script, "")?;

        writeln!(script, "    print(\"Witness files written. Run:\")")?;
        writeln!(script, "    print(\"  circom circuit.circom --r1cs --wasm\")")?;
        writeln!(script, "    print(\"  snarkjs groth16 prove ... input_a.json\")")?;
        writeln!(script, "")?;

        writeln!(script, "if __name__ == \"__main__\":")?;
        writeln!(script, "    main()")?;

        Ok(script)
    }

    /// Generate JSON witness file
    fn generate_json(&self, finding: &Finding) -> anyhow::Result<String> {
        #[derive(Serialize)]
        struct PoCJson {
            attack_type: String,
            severity: String,
            description: String,
            witness_a: Vec<String>,
            witness_b: Option<Vec<String>>,
            public_inputs: Vec<String>,
            location: Option<String>,
        }

        let poc_json = PoCJson {
            attack_type: format!("{:?}", finding.attack_type),
            severity: format!("{:?}", finding.severity),
            description: finding.description.clone(),
            witness_a: finding.poc.witness_a.iter().map(|fe| fe.to_hex()).collect(),
            witness_b: finding.poc.witness_b.as_ref().map(|w| w.iter().map(|fe| fe.to_hex()).collect()),
            public_inputs: finding.poc.public_inputs.iter().map(|fe| fe.to_hex()).collect(),
            location: finding.location.clone(),
        };

        Ok(serde_json::to_string_pretty(&poc_json)?)
    }

    /// Convert witness to JSON format for circuit input
    fn witness_to_json(&self, witness: &[FieldElement]) -> anyhow::Result<String> {
        let mut json = String::from("{\n");
        for (i, fe) in witness.iter().enumerate() {
            let comma = if i < witness.len() - 1 { "," } else { "" };
            writeln!(json, "  \"input_{}\": \"{}\"{}",  i, fe.to_hex(), comma)?;
        }
        json.push_str("}");
        Ok(json)
    }

    /// Generate PoC for all findings and save to directory
    pub fn generate_all(
        &self,
        findings: &[Finding],
        output_dir: &std::path::Path,
        format: PoCFormat,
    ) -> anyhow::Result<()> {
        std::fs::create_dir_all(output_dir)?;

        for (i, finding) in findings.iter().enumerate() {
            let extension = match format {
                PoCFormat::Shell => "sh",
                PoCFormat::JavaScript => "js",
                PoCFormat::Rust => "rs",
                PoCFormat::Python => "py",
                PoCFormat::Json => "json",
            };

            let filename = format!(
                "poc_{:02}_{:?}.{}",
                i + 1,
                finding.attack_type,
                extension
            ).to_lowercase().replace(" ", "_");

            let script = self.generate(finding, format)?;
            let path = output_dir.join(&filename);
            std::fs::write(&path, script)?;

            tracing::info!("Generated PoC: {:?}", path);
        }

        Ok(())
    }
}

impl Default for PoCGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use zk_core::{AttackType, Severity, ProofOfConcept, Finding};

    fn sample_finding() -> Finding {
        Finding {
            attack_type: AttackType::Underconstrained,
            severity: Severity::Critical,
            description: "Path indices not constrained to binary values".to_string(),
            poc: ProofOfConcept {
                witness_a: vec![
                    FieldElement::from_u64(1),
                    FieldElement::from_u64(0),
                    FieldElement::from_u64(1),
                ],
                witness_b: Some(vec![
                    FieldElement::from_u64(1),
                    FieldElement::from_u64(2),  // Invalid: not 0 or 1
                    FieldElement::from_u64(1),
                ]),
                public_inputs: vec![FieldElement::from_u64(12345)],
                proof: None,
            },
            location: Some("merkle.circom:42".to_string()),
        }
    }

    #[test]
    fn test_generate_shell() {
        let generator = PoCGenerator::new();
        let finding = sample_finding();

        let script = generator.generate(&finding, PoCFormat::Shell).unwrap();

        assert!(script.contains("#!/bin/bash"));
        assert!(script.contains("Underconstrained"));
        assert!(script.contains("input_a.json"));
        assert!(script.contains("input_b.json"));
    }

    #[test]
    fn test_generate_javascript() {
        let generator = PoCGenerator::new();
        let finding = sample_finding();

        let script = generator.generate(&finding, PoCFormat::JavaScript).unwrap();

        assert!(script.contains("snarkjs"));
        assert!(script.contains("witnessA"));
        assert!(script.contains("witnessB"));
        assert!(script.contains("VULNERABILITY CONFIRMED"));
    }

    #[test]
    fn test_generate_rust() {
        let generator = PoCGenerator::new();
        let finding = sample_finding();

        let script = generator.generate(&finding, PoCFormat::Rust).unwrap();

        assert!(script.contains("#[test]"));
        assert!(script.contains("witness_a"));
        assert!(script.contains("witness_b"));
    }

    #[test]
    fn test_generate_json() {
        let generator = PoCGenerator::new();
        let finding = sample_finding();

        let json = generator.generate(&finding, PoCFormat::Json).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();

        assert_eq!(parsed["attack_type"], "Underconstrained");
        assert_eq!(parsed["severity"], "Critical");
    }
}
